### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by invig** [seattlerb/omnifocus-redmine#1]
I'm getting the following error trying to execute: 

/Library/Ruby/Gems/1.8/gems/mechanize-0.9.3/lib/www/mechanize.rb:562:in `fetch_page': 401 => Net::HTTPUnauthorized (WWW::Mechanize::ResponseCodeError)

Is auth configurable as a paramater?

**Comment by kushali** [comment]
Auth is not a configurable parameter.  I'll look into adding it soon.

**Comment by kushali** [comment]
I just released a new version of the gem that supports authorization.  Let me know if you have any issues with it.

You'll need to add username and password to your .omnifocus-redmine file.

**Comment by zenspider** [comment]
I'm assuming this is closed.
