### ISSUE TITLE
Sync doesn't work

### ISSUE THREAD

**Issue by bollinim** [seattlerb/omnifocus-redmine#10]
Hi,

i'm an OmniFocus 2.0 user and our company rely on Redmine as a PM tool.
I've just installed omnifocus-redmine and set up .omnifocus-redmine.yml as follow:
user_id: '1'
redmine_url: https://projects.met.it
username: My redmine Username (LDAP Auth)
password: My Redmine Password (LDAP  Auth)
just_project: false 

After launching OF SYNC i got the following errors:

/Library/Ruby/Gems/2.0.0/gems/rb-appscript-0.6.1/lib/_appscript/terminology.rb:57: warning: assigned but unused variable - rev
scanning redmine
mechanize/cookie will be deprecated.  Please migrate to the http-cookie APIs.
mechanize/cookie_jar will be deprecated.  Please migrate to the http-cookie APIs.
/Library/Ruby/Gems/2.0.0/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:651:in `resolve': absolute URL needed (not /issues.xml?assigned_to_id=) (ArgumentError)
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:223:in`fetch'
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.7.3/lib/mechanize.rb:440:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-redmine-1.2.5/lib/omnifocus/redmine.rb:59:in`process_query_results'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-redmine-1.2.5/lib/omnifocus/redmine.rb:46:in `populate_redmine_tasks'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-2.1.4/lib/omnifocus.rb:226:in`block in cmd_sync'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-2.1.4/lib/omnifocus.rb:223:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-2.1.4/lib/omnifocus.rb:223:in`cmd_sync'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-2.1.4/lib/omnifocus.rb:251:in `method_missing'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-2.1.4/bin/of:17:in`<top (required)>'
    from /usr/bin/of:23:in `load'
    from /usr/bin/of:23:in`<main>'

Can you help me? I wasn't able to figure out what's wrong with my configuration

**Comment by zenspider** [comment]
I have NO idea of the omnifocus gem works against omnifocus 2.0. Currently I'm using 1.x and my initial applescript tests against omnifocus 2 have not been very happy.

That said, you're not having an applescript (OSA) problem (yet). I do have one unreleased change for auth problems. 

Can you try modifying your redmine_url value to have a trailing slash? Mine has:

:redmine_url: http://bugs.ruby-lang.org/

**Comment by bollinim** [comment]
Hi Ryan,
Thank you for your reply.
After my posted request I figured out why my setup wasn't working. I had deleted by mistake the colon in front of the URL variable. By the way I've noticed that I cannot decide the name of the folder name containing RM projects and dates are not synced and I think they are very important missing functionalities.
Thank you

Michele Bollini
Owner - Project Manager
Information and Communication Technology

T. +39 02 72546471
F. +39 02 70031282
M. +39 328 1555270
michele.bollini@met.it
Skype michele.bollini

MET S.r.l.
via Torino, 2
20123 Milano (MI) Italy
www.met.it

CONSIDER THE ENVIRONMENT. PLEASE DO NOT PRINT THIS EMAIL UNLESS YOU REALLY NEED TO.

THIS E-MAIL AND ANY ATTACHED FILES ARE CONFIDENTIAL, PROTECTED BY COPYRIGHT AND MAY BE LEGALLY PRIVILEGED.
This message is intended only for the use of the addressee and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this e-mail in error, please notify us immediately by return e-mail and delete this e-mail and all attachments from your system.

**Comment by zenspider** [comment]
Please file one problem description per issue. If you have multiple problems, please file multiple issues so they can be fixed and tracked independently.

If this issue is resolved, please close.
