### ISSUE TITLE
can't get this to work - is it me?

### ISSUE THREAD

**Issue by marfarma** [seattlerb/omnifocus-redmine#2]
I find the documentation a little spare, so I am not confident that I'm not missing a step.  But with a ~/.omnifocus-redmine.yml like this (updated with my particulars):

<pre>

---
user_id: 20
redmine_url: http://redmine/
username: me
password: 1234
queries: ["status_id=1", "status_id=2"]
just_project: true
</pre>

the command:

<pre>
$ omnifocus
</pre>

converts my ~/.omnifocus-redmine.yml to a zero length file and returns this error:

<pre>
$ omnifocus
/Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/rb-appscript-0.6.1/lib/_appscript/terminology.rb:57: warning: assigned but unused variable - rev
scanning redmine
/Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:19:in `block in load_or_create_redmine_config': undefined method `dump' for YAML:Module (NoMethodError)
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:18:in `open'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:18:in `load_or_create_redmine_config'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:29:in `populate_redmine_tasks'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-1.5.2/lib/omnifocus.rb:222:in `block in run'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-1.5.2/lib/omnifocus.rb:219:in `each'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-1.5.2/lib/omnifocus.rb:219:in `run'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-1.5.2/lib/omnifocus.rb:67:in `run'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-1.5.2/bin/omnifocus:6:in `<top (required)>'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/bin/omnifocus:19:in `load'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/bin/omnifocus:19:in `<main>'
</pre>

So - is it just me?

**Comment by marfarma** [comment]
Note: I've tried using ree ruby, Lion's system ruby, as well as the 1.9.3 I just posted the error from.  None of them worked, although there was a slight variations in the error message that was returned.

**Comment by marfarma** [comment]
did a gem update --system, which upgraded rubygems -- then did a gem update to pick up any lagging updates.  The error message changed to: 

<pre>
$ omnifocus redmine
/Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/rb-appscript-0.6.1/lib/_appscript/terminology.rb:57: warning: assigned but unused variable - rev
scanning redmine
/Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:19:in `block in load_or_create_redmine_config': uninitialized constant OmniFocus::Redmine::YAML (NameError)
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:18:in `open'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:18:in `load_or_create_redmine_config'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:29:in `populate_redmine_tasks'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-1.5.2/lib/omnifocus.rb:222:in `block in run'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-1.5.2/lib/omnifocus.rb:219:in `each'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-1.5.2/lib/omnifocus.rb:219:in `run'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-1.5.2/lib/omnifocus.rb:67:in `run'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/omnifocus-1.5.2/bin/omnifocus:6:in `<top (required)>'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/bin/omnifocus:19:in `load'
    from /Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/bin/omnifocus:19:in `<main>'
</pre>


I added 'require yaml' at the top of redmine.rb and the YAML error went away -- making progress:

<pre>
$ omnifocus redmine
/Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/rb-appscript-0.6.1/lib/_appscript/terminology.rb:57: warning: assigned but unused variable - rev
scanning redmine
Created default config in /Users/pauliprice/.omnifocus-redmine.yml. Go fill it out.
</pre>


I update with my credentials, and then get this:

<pre>
$ omnifocus redmine
/Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/rb-appscript-0.6.1/lib/_appscript/terminology.rb:57: warning: assigned but unused variable - rev
scanning redmine
/Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/mechanize-1.0.0/lib/mechanize.rb:442: warning: assigned but unused variable - chain
/Users/pauliprice/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
/Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/mechanize-1.0.0/lib/mechanize/chain/uri_resolver.rb:28:in `block in handle': warning: URI.escape is obsolete
/Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/mechanize-1.0.0/lib/mechanize/monkey_patch.rb:6: warning: instance variable @seems_1_0_server not initialized
/Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/mechanize-1.0.0/lib/mechanize/chain/uri_resolver.rb:28:in `block in handle': warning: URI.escape is obsolete
/Users/pauliprice/.rvm/gems/ruby-1.9.3-p0/gems/mechanize-1.0.0/lib/mechanize/monkey_patch.rb:6: warning: instance variable @seems_1_0_server not initialized
</pre>


Noting that they were warnings, rather than errors, I checked my omnifocus file - no new entries.

**Comment by marfarma** [comment]
Noted that the REST API access was not enabled on my server -- fixed that and retried.  Results were the same as before - same warnings, no tasks transferred.

**Comment by kushali** [comment]
I'll look into on December 13th. I'm using it with 1.8 daily.  I don't use a username and password though so that might be the issue.

If this helps this is my .omnifocus-redmine file:

---

:user_id: 20
:redmine_url: http://redmine/redmine
:queries: ["status_id=1", "status_id=9", "status_id=2"]
:just_project: true

**Comment by marfarma** [comment]
fyi: my url is https://subdomain.example.com - with a self-signed certificate backing the SSL 

nothing in the error messages seemed related to SSL support, so didn't mention it till now - but thought I'd let you know, in case it matters for the authentication support

**Comment by kushali** [comment]
I'm relatively certain there isn't an issue with your redmine server or your .omnifocus-redmine file.  If the .omnifocus-redmine config isn't parsing correctly all of the mechanize steps beyond that are suspect.  My first thought is that the config file format the gem uses isn't compatible with the 1.9.3 YAML parser.  I haven't tested it with 1.9.3.

I'll keep looking into it but can you try it with the Lion ruby (should be 1.8.7) and paste in the error you receive?  Can you also tell me what version of ruby gems you are using in your rvm setup with 1.9.3?  I'll try to recreate your setup with my redmine configuration and fix the underlying issue.

**Comment by zenspider** [comment]
No feedback from the OP for 2 weeks. I'm assuming this is fixed. Closing.
