### ISSUE TITLE
quick start

### ISSUE THREAD

**Issue by okliv** [seattlerb/omnifocus-redmine#3]
$ omnifocus redmine

/.../.rvm/gems/ruby-1.9.2-p290@redmine/gems/rb-appscript-0.6.1/lib/_aem/findapp.rb:30:in `rescue in _find_app': Application "[\"OmniFocus.app\"]" not found. (FindApp::ApplicationNotFoundError)

or redmine server has to be local for omnifocus?!?

**Comment by zenspider** [comment]
On Feb 28, 2012, at 15:14 , okliv wrote:

> $ omnifocus redmine
> 
> /.../.rvm/gems/ruby-1.9.2-p290@redmine/gems/rb-appscript-0.6.1/lib/_aem/findapp.rb:30:in `rescue in _find_app': Application "[\"OmniFocus.app\"]" not found. (FindApp::ApplicationNotFoundError)
> 
> or redmine server has to be local for omnifocus?!?

That's saying it can't find your omnifocus application.

**Comment by okliv** [comment]
i've understood error message, but question is why is it so? this plugin will work only if omnifocus would situate on same computer with redmine server?

**Comment by okliv** [comment]
in other words: i have redmine running on remote server and i'am using omnifocus on my notebook... is it possible to sync issues?

**Comment by okliv** [comment]
is it plugin at all? )) ahhh... i think i got it... it is standalone app for my note... is it?

**Comment by okliv** [comment]
ok@okbook~$ ruby -v
ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-darwin10]
ok@okbook~$ omnifocus redmine
/opt/local/lib/ruby/vendor_ruby/1.8/rubygems.rb:779:in `report_activate_error': Could not find RubyGem omnifocus (>= 0) (Gem::LoadError)
    from /opt/local/lib/ruby/vendor_ruby/1.8/rubygems.rb:214:in`activate'
    from /opt/local/lib/ruby/vendor_ruby/1.8/rubygems.rb:1082:in `gem'
    from /opt/local/bin/omnifocus:18

**Comment by zenspider** [comment]
On Feb 28, 2012, at 15:21 , okliv wrote:

> in other words: i have redmine running on remote server and i'am using omnifocus on my notebook... is it possible to sync issues?

I don't think this has anything to do with the redmine plugin. The omnifocus cmdline tool can't find your OmniFocus.app. Does `open -a OmniFocus` work in your shell?

**Comment by okliv** [comment]
yes, locally installed Omnifocus works... but...  

ok@okbook~$ sudo omnifocus redmine
omnifocus is going away. Use `of sync` instead.
scanning redmine
/opt/local/lib/ruby/gems/1.8/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:19:in `load_or_create_redmine_config': uninitialized constant OmniFocus::Redmine::YAML (NameError)
    from /opt/local/lib/ruby/gems/1.8/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:18:in`open'
    from /opt/local/lib/ruby/gems/1.8/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:18:in `load_or_create_redmine_config'
    from /opt/local/lib/ruby/gems/1.8/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:29:in`populate_redmine_tasks'
    from /opt/local/lib/ruby/gems/1.8/gems/omnifocus-2.0.0/lib/omnifocus.rb:222:in `send'
    from /opt/local/lib/ruby/gems/1.8/gems/omnifocus-2.0.0/lib/omnifocus.rb:222:in`cmd_sync'
    from /opt/local/lib/ruby/gems/1.8/gems/omnifocus-2.0.0/lib/omnifocus.rb:219:in `each'
    from /opt/local/lib/ruby/gems/1.8/gems/omnifocus-2.0.0/lib/omnifocus.rb:219:in`cmd_sync'
    from /opt/local/lib/ruby/gems/1.8/gems/omnifocus-2.0.0/lib/omnifocus.rb:245:in `send'
    from /opt/local/lib/ruby/gems/1.8/gems/omnifocus-2.0.0/lib/omnifocus.rb:245:in`method_missing'
    from /opt/local/lib/ruby/gems/1.8/gems/omnifocus-2.0.0/bin/omnifocus:7
    from /opt/local/bin/omnifocus:19:in `load'
    from /opt/local/bin/omnifocus:19

**Comment by zenspider** [comment]
I suspect the email gateway is either slow or broken so I'm pasting this in here... Sorry if a duplicate shows up:

This is your 3rd possibly unrelated error message. At this stage I'm confused what I'm supposed to look at. Can you please only file one problem per issue?

**Comment by okliv** [comment]
sorry if i made some noise...

than let it be one issue: "installation", or "quick start"

with three sub issues:
- misunderstanding what is it at all (not an issue, just my inattention or lack of project description)
- error with dependencies (it asked me if i have omnifocus gem installed - i fixed it with "gem install omnifocus")
- now topical problem is - https://github.com/seattlerb/omnifocus-redmine/issues/3#issuecomment-4228521

**Comment by zenspider** [comment]
1 issue with 3 sub issues is 4 issues.
