### ISSUE TITLE
YAML.load in redmine.rb throws error

### ISSUE THREAD

**Issue by jameskyle** [seattlerb/omnifocus-redmine#4]
Ruby: 1.9.2-p318
Omnifocus-redmine: 1.2.3
Symptom: YAML.load method is unresolvable
Fix: Insert require 'yaml' in redmine.rb before call to load

% omnifocus
    ruby-1.9.2-p318/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:18:in `block in load_or_create_redmine_config': undefined method`dump' for YAML:Module (NoMethodError)
            from /Users/jkyle/.rvm/gems/ruby-1.9.2-p318/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:17:in `open'
        from /Users/jkyle/.rvm/gems/ruby-1.9.2-p318/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:17:in`load_or_create_redmine_config'
        from /Users/jkyle/.rvm/gems/ruby-1.9.2-p318/gems/omnifocus-redmine-1.2.3/lib/omnifocus/redmine.rb:28:in `populate_redmine_tasks'
        from /Users/jkyle/.rvm/gems/ruby-1.9.2-p318/gems/omnifocus-1.5.2/lib/omnifocus.rb:222:in`block in run'
        from /Users/jkyle/.rvm/gems/ruby-1.9.2-p318/gems/omnifocus-1.5.2/lib/omnifocus.rb:219:in `each'
        from /Users/jkyle/.rvm/gems/ruby-1.9.2-p318/gems/omnifocus-1.5.2/lib/omnifocus.rb:219:in`run'
        from /Users/jkyle/.rvm/gems/ruby-1.9.2-p318/gems/omnifocus-1.5.2/lib/omnifocus.rb:67:in `run'
        from /Users/jkyle/.rvm/gems/ruby-1.9.2-p318/gems/omnifocus-1.5.2/bin/omnifocus:6:in`<top (required)>'
        from /Users/jkyle/.rvm/gems/ruby-1.9.2-p318/bin/omnifocus:19:in `load'
        from /Users/jkyle/.rvm/gems/ruby-1.9.2-p318/bin/omnifocus:19:in`<main>'

Putting a 'require "yaml"' in redmine.rb before any yaml methods are called eliminates the error.

```
% omnifocus
scanning redmine
Created default config in /Users/jkyle/.omnifocus-redmine.yml. Go fill it out.
```

**Comment by kushali** [comment]
Committed patch. Will be in next release.
