### ISSUE TITLE
Auth via API key

### ISSUE THREAD

**Issue by alanbrent** [seattlerb/omnifocus-redmine#6]
Would it be possible to do this rather than password auth? Our redmine is using LDAP auth against our AD credentials...I'd rather avoid putting that in plaintext.

**Comment by zenspider** [comment]
I... have no idea. I'm open to a patch, but I can't implement this because I don't have anything to test against.

**Comment by zenspider** [comment]
Looks like this is a non-issue at this point. If someone wants to send in a PR, I'll blindly merge it. Until then?
