### ISSUE TITLE
Not syncing due dates

### ISSUE THREAD

**Issue by ghost** [seattlerb/omnifocus-redmine#7]
Is it correct, that omnifocus-redmine is not syncing the due date of an issue to the omnifocus task? Or am I doing something wrong?

**Comment by zenspider** [comment]
You are reading the code correctly. It currently doesn't do anything for the due dates. Right now there is no support for it in omnifocus (the gem), but I bet it could be added without _too much_ trouble. The only complication I can come up with is making sure the dates stay synced (one directory only is fine).

**Comment by ghost** [comment]
One direction only would be fine with me, as also checked off tasks in OmniFocus get re-opened by your gem. Having to make the necessary changes in Redmine is not a showstopper for me. However, not knowing when the task is due (and possibly starts, if we are at it), is a showstopper for me, as I depend heavily on that with my custom perspectives.

**Comment by zenspider** [comment]
This isn't a priority for me, but if you want to take a whack at it, go for it. There will have to be a change in the omnifocus (OF) gem to set the date if available (some bug systems, like github, don't have due dates) and a corresponding change in OFRM to get the date from each ticket if set.

This makes a further complication I didn't consider before. Right now, OF only deals with "does it exist" and "is it closed/open". If you change a title in the bug db, it won't sync that change. Likewise, if you change a due date, it won't sync the change. Changing due dates seems much more likely than titles (the way I work at least). I don't know if that's a problem for the way you work.

**Comment by zenspider** [comment]
Seems like this is not a priority. Closing.
